# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the CC-by-NC license found in the
# LICENSE file in the root directory of this source tree.
from typing import Union

from .discrete_unet import DiscreteUNetModel
from .ema import EMA
from .unet import UNetModel

MODEL_CONFIGS = {
    "unet_uncond": {
        "in_channels": 1,
        "model_channels": 4,
        "out_channels": 1,
        "num_res_blocks": 1,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": 7,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 4,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },

    "unet_cond": {
        "in_channels": 2,
        "model_channels": 4,
        "out_channels": 1,
        "num_res_blocks": 1,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": 7,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 4,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },
    "unet_uncond_large": {
        "in_channels": 1,
        "model_channels": 4,
        "out_channels": 1,
        "num_res_blocks": 32,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": 7,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 4,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },

    "unet_uncond_xlarge": {
        "in_channels": 1,
        "model_channels": 16,
        "out_channels": 1,
        "num_res_blocks": 3,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": 7,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 16,
        "use_scale_shift_norm": True,
        "resblock_updown": True,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },

    "unet_cond_large": {
        "in_channels": 2,
        "model_channels": 4,
        "out_channels": 1,
        "num_res_blocks": 32,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": 7,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 4,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },

    "unet_cond_xlarge": {
        "in_channels": 2,
        "model_channels": 16,
        "out_channels": 1,
        "num_res_blocks": 3,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": 7,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 16,
        "use_scale_shift_norm": True,
        "resblock_updown": True,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },

    "unet_uncond_neutral": {
        "in_channels": 1,
        "model_channels": 4,
        "out_channels": 1,
        "num_res_blocks": 1,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": None,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 4,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },

    "unet_cond_neutral": {
        "in_channels": 2,
        "model_channels": 4,
        "out_channels": 1,
        "num_res_blocks": 1,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": None,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 4,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },
    "unet_uncond_neutral_large": {
        "in_channels": 1,
        "model_channels": 4,
        "out_channels": 1,
        "num_res_blocks": 32,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": None,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 4,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },
    "unet_cond_neutral_large": {
        "in_channels": 2,
        "model_channels": 4,
        "out_channels": 1,
        "num_res_blocks": 32,
        "dims": 3,
        "attention_resolutions": [8],
        "dropout": 0.1,
        "channel_mult": [1, 2, 2, 4],
        "num_classes": None,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 4,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        "input_downscale": 2,
    },
    "unet_uncond_neutral_xlarge": {
        "in_channels": 1,
        # Reduced base channels to cut activations and parameter size.
        "model_channels": 16,
        "out_channels": 1,
        # Fewer residual blocks (was 32) – main memory saver.
        "num_res_blocks": 3,
        "dims": 3,
        # Restrict attention to coarser scale only to save memory.
        "attention_resolutions": [8],
        "dropout": 0.1,
        # Slightly narrower top levels; keep depth but lower width.
        "channel_mult": [1, 2, 2, 4],
        "num_classes": None,
        # Enable gradient checkpointing to trade compute for memory.
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 16,
        "use_scale_shift_norm": True,
        "resblock_updown": True,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        # Keep single upscale stage.
        "input_downscale": 2,
    },
    "unet_cond_neutral_xlarge": {
        "in_channels": 2,
        # Reduced base channels to cut activations and parameter size.
        "model_channels": 16,
        "out_channels": 1,
        # Fewer residual blocks (was 32) – main memory saver.
        "num_res_blocks": 3,
        "dims": 3,
        # Restrict attention to coarser scale only to save memory.
        "attention_resolutions": [8],
        "dropout": 0.1,
        # Slightly narrower top levels; keep depth but lower width.
        "channel_mult": [1, 2, 2, 4],
        "num_classes": None,
        # Enable gradient checkpointing to trade compute for memory.
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": 16,
        "use_scale_shift_norm": True,
        "resblock_updown": True,
        "use_new_attention_order": True,
        "with_fourier_features": False,
        # Keep single upscale stage.
        "input_downscale": 2,
    },
        # "imagenet": {
    #     "in_channels": 2,
    #     "model_channels": 2,
    #     "out_channels": 1,
    #     "num_res_blocks": 1,
    #     "dims": 3,
    #     "attention_resolutions": [1, 2, 2],
    #     "dropout": 0.1,
    #     "channel_mult": [1, 2, 4],
    #     "num_classes": None,
    #     "use_checkpoint": False,
    #     "num_heads": 1,
    #     "num_head_channels": 2,
    #     "use_scale_shift_norm": True,
    #     "resblock_updown": False,
    #     "use_new_attention_order": True,
    #     "with_fourier_features": False,
    # },
    "imagenet_discrete": {
        "in_channels": 3,
        "model_channels": 192,
        "out_channels": 3,
        "num_res_blocks": 4,
        "attention_resolutions": [2, 4, 8],
        "dropout": 0.2,
        "channel_mult": [2, 3, 4, 4],
        "num_classes": 1000,
        "use_checkpoint": False,
        "num_heads": -1,
        "num_head_channels": 64,
        "use_scale_shift_norm": True,
        "resblock_updown": True,
        "use_new_attention_order": True,
        "with_fourier_features": False,
    },
    "cifar10": {
        "in_channels": 3,
        "model_channels": 128,
        "out_channels": 3,
        "num_res_blocks": 4,
        "attention_resolutions": [2],
        "dropout": 0.3,
        "channel_mult": [2, 2, 2],
        "conv_resample": False,
        "dims": 2,
        "num_classes": None,
        "use_checkpoint": False,
        "num_heads": 1,
        "num_head_channels": -1,
        "num_heads_upsample": -1,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
    },
    "cifar10_discrete": {
        "in_channels": 3,
        "model_channels": 96,
        "out_channels": 3,
        "num_res_blocks": 5,
        "attention_resolutions": [2],
        "dropout": 0.4,
        "channel_mult": [3, 4, 4],
        "conv_resample": False,
        "dims": 2,
        "num_classes": None,
        "use_checkpoint": False,
        "num_heads": -1,
        "num_head_channels": 64,
        "num_heads_upsample": -1,
        "use_scale_shift_norm": True,
        "resblock_updown": False,
        "use_new_attention_order": True,
        "with_fourier_features": False,
    },
}


def instantiate_model(
    architechture: str, is_discrete: bool, use_ema: bool
) -> Union[UNetModel, DiscreteUNetModel]:
    assert (
        architechture in MODEL_CONFIGS
    ), f"Model architecture {architechture} is missing its config."

    if is_discrete:
        if architechture + "_discrete" in MODEL_CONFIGS:
            config = MODEL_CONFIGS[architechture + "_discrete"]
        else:
            config = MODEL_CONFIGS[architechture]
        model = DiscreteUNetModel(
            vocab_size=257,
            **config,
        )
    else:
        model = UNetModel(**MODEL_CONFIGS[architechture])

    if use_ema:
        return EMA(model=model)
    else:
        return model
